server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: warehouse
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:warehouse;DB_CLOSE_DELAY=-1
    jpa:
      hibernate:
        ddl-auto: drop-create
    username: sa
    password: sa
  h2:
    console:
      enabled: true
